### PR TITLE
Link checker exclusions, fixes

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: Chip Zoller <chipzoller@gmail.com>

* Introduces a skip file for the link checker
* Goes through found issues and corrects as many as possible which don't require discussion

### CODE REVIEW

**Review by robfaraj — APPROVED** [review]
lgtm!

**Review by srpomeroy — DISMISSED** [review]
LGTM!

**Comment by chipzoller** [comment]
Needs review from @bstuder99

**Comment by bstuder99** [comment]
So in the future, we can blacklist additional links from appearing in this link checker by adding them to .lycheeignore?

**Review by bstuder99 — APPROVED** [review]

**Comment by chipzoller** [comment]
Yes

**Pull request merged**
