### PR TITLE
federation updates

### PR DESCRIPTION
**Pull request by jessegoodier**
Summary:
1. changing federation doc to overview the options
2. move thanos setup to own doc
3. add detail/diagram to federated-etl doc
4. update multi-cluster options to differentiate editions

@bstuder99 Do you mind checking the nav/formatting/image links? I realize that is asking a lot, feel free to push back. This is not super time sensitive.

@srpomeroy Do you mind doing a full review? There are a lot of changes.

All others, feedback welcome!

### CODE REVIEW

**Review by bstuder99 — APPROVED** [review]

**Comment by thomasvn** [comment]
@jessegoodier This looks awesome!! As a future todo, it may be good to ensure greater consistency between the Thanos & ETL Federation architecture diagrams. For example, one shows Billing Data integration while the other does not. Could be confusing for some users.

A few todos for this PR (may need input from @bstuder99 for docs product decisions here):

* Let's get `thanos-setup.md` into `SUMMARY.md`?
* `federated-clusters.md` and `multi-cluster.md` currently sit under "Advanced Configuration" in the `SUMMARY.md` nav. We should move that into "Installation"?
* We should consider merging `federated-clusters.md` and `multi-cluster.md`? They both present pretty similar information.

**Comment by bstuder99** [comment]
@thomasvn 
Would support the merging of the Multi Cluster and Federated Cluster docs, but would Installation make sense? Unless this is required for using Kubecost out of the box, I would consider it more of an Advanced Config content.

**Comment by robfaraj** [comment]
lgtm!

**Comment by jessegoodier** [comment]
merged them. please take a look.

**Comment by bstuder99** [comment]
I've combed for any links and it looks like we weren't linking to federated-clusters.md anywhere. So the final step is adjusting summary.md:
* Federated-clusters.md to be removed
* Federated-etl.md to be added

**Comment by jessegoodier** [comment]
> I've combed for any links and it looks like we weren't linking to federated-clusters.md anywhere. So the final step is adjusting summary.md:
> 
> * Federated-clusters.md to be removed
> * Federated-etl.md to be added

awesome, I think this is good to go.

@srpomeroy, you have any concerns?

**Comment by thomasvn** [comment]
@jessegoodier or @bstuder99 Could you add the following to the `SUMMARY.md` file so these docs show up in the navbar? Feel free to adjust how I organized it if you feel differently!

```txt
  * [Multi-Cluster](multi-cluster.md)
    * [Federated ETL](federated-etl.md)
    * [Thanos Federation](thanos-setup.md)
      * [Configuring Thanos](long-term-storage.md)
      * [Secondary Clusters Guide](secondary-clusters.md)
      * [Thanos Upgrade](thanos-upgrade.md)
    * [AWS](install-and-configure/install/long-term-storage/aws/README.md)
      * [AWS Multi-Cluster Storage Configuration](long-term-storage-aws.md)
      * [Creating a Thanos IAM policy](aws-service-account-thanos.md)
    * [Azure](install-and-configure/install/long-term-storage/azure/README.md)
      * [Azure Long Term Storage](long-term-storage-azure.md)
    * [GCP](install-and-configure/install/long-term-storage/gcp/README.md)
      * [GCP Long Term Storage](long-term-storage-gcp.md)
```

**Comment by srpomeroy** [comment]
As soon as the `SUMMARY.md` changes are made we should be good!

**Comment by srpomeroy** [comment]
`.gitbook.yaml` has some redirects from ZD that need to be updated.
https://github.com/kubecost/docs/blob/c6e9e701eb003cd097e812b2ccb8fab0f5b3a24b/.gitbook.yaml#L34
https://github.com/kubecost/docs/blob/c6e9e701eb003cd097e812b2ccb8fab0f5b3a24b/.gitbook.yaml#L136

**Review by srpomeroy — APPROVED** [review]

**Comment by jessegoodier** [comment]
thanks all! nice work.

**Pull request merged**
