### PR TITLE
Updates CCE to explain topNitems

### PR DESCRIPTION
**Pull request by bstuder99**

### CODE REVIEW

**Comment by dwbrown2** [comment]
@bstuder99 worth adding a tag/header to James can directly link to this?

**Comment by dwbrown2** [comment]
Otherwise, LGTM!

**Comment by jjarrett21** [comment]
just let me know when you have the full link, I've got all of the other copy updated on my PR

**Comment by dwbrown2** [comment]
> @bstuder99 worth adding a tag/header to James can directly link to this?

Brett, to clarify this proposal... I think this can be it's own section on item-level sample... it's a meaningful concept. Just an idea.

**Comment by bstuder99** [comment]
Do you mean the full link being added to the UI? It should be: https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/cloud-costs-explorer#add-filters

**Comment by bstuder99** [comment]
Gotcha, let me try and restructure

**Comment by bstuder99** [comment]
Link should be: https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/cloud-costs-explorer#using-topnitems

**Pull request merged**
