### PR TITLE
Creates Cluster Right Sizing Rec API doc

### PR DESCRIPTION
**Pull request by bstuder99**
## Proposed Changes

New Cluster Right Sizing API doc, has already received a review from Niko but is being manually ported from GitBook into GitHub due to errors in architecture of repo after merging the CR

### CODE REVIEW

**Comment by kwombach12** [comment]
@bstuder99 I'm seeing a lot of funkiness when I view the file 
Screenshot 2023-10-18 at 5 21 36 PM

**Comment by bstuder99** [comment]
It's supposed to look like that in the GH Preview feature. This is just the copied raw text from the GitBook-generated article, so it should display the same. I had some issues with the change request so I'm manually porting it

**Review by nikovacevic — APPROVED** [review]

**Review by kwombach12 — APPROVED** [review]
LGTM

**Comment by thomasvn** [comment]
@bstuder99 Was it intentional that you don't have this doc in `SUMMARY.md` yet?

**Comment by bstuder99** [comment]
Nope, good catch

**Comment by bstuder99** [comment]
Updated in https://github.com/kubecost/docs/pull/777

**Pull request merged**
