### PR TITLE
Image refactoring

### PR DESCRIPTION
**Pull request by chipzoller**
This PR is cleanup/organizational in nature and should be almost completely transparent to users. It does the following:

* Moves all images into `/images` and non-images into `/assets`
* Cleans and standardizes on image names
* All images now have captions/alt text
* Removes any unreferenced images
* Standardizes on how image paths are referenced
* Fetches all externally-linked images and stores them in this repo. Any images referenced in this documentation should be kept in this repo and not externally referenced.
* Tacit misspellings and minor Markdown-related formatting issues.

[This link](https://chips-organization.gitbook.io/kubecost-docs/) can be used to preview the changes proposed in this PR.

### CODE REVIEW

**Review by bstuder99 — DISMISSED** [review]

**Comment by srpomeroy** [comment]
> Why is there no GitBook preview showing with this PR?
https://docs.gitbook.com/product-tour/git-sync/github-pull-request-preview#security-considerations
```
For security reasons, GitBook by default does not currently generate previews for PRs opened from forks of your repository: because the content of the PR preview is accessible under your own domain, whether on .gitbook.io or your , a user could generate malicious content in a fork of your public repository and have it served under your name.
We allow users to explicitly configure this through a new option in the Git Sync settings.
```

**Comment by chipzoller** [comment]
Ok, so how do we ensure that such PRs are safe to merge? Is there another mechanism we should use?

**Comment by srpomeroy** [comment]
Good question... @teevans thoughts on enabling "Fork Pull-Request Preview" on the Docs GitBook Space?

**Comment by jessegoodier** [comment]
@bstuder99 I know there's a ton of changes here, but looks good to me. 

Do you have time to review this week?

**Comment by bstuder99** [comment]
The looks fine with me and I don't see why this shouldn't deploy correctly, but I suggested we try this with a couple images first just to see what happens. If you feel this is good to merge, then I'll support it.

**Review by bstuder99 — APPROVED** [review]

**Comment by srpomeroy** [comment]
> The looks fine with me and I don't see why this shouldn't deploy correctly, but I suggested we try this with a couple images first just to see what happens. If you feel this is good to merge, then I'll support it.

I concur with testing with a handful first. Especially the ones that are managed by the GitBook editor (anything in `.gitbook/assets`).

**Pull request merged**
