### PR TITLE
Modify release process.md

### PR DESCRIPTION
**Pull request by teevans**

### CODE REVIEW

**Comment by teevans** [comment]
@dwbrown2 & @kwombach12 - This is a rough first draft of the pushing release communication we mentioned earlier. What are your thoughts?

**Review by bstuder99 — DISMISSED** [review]

**Comment by dwbrown2** [comment]
Like the start! Can we make more specific on our deliverables? i.e. we will always aim to have an RC by release date even when we're working through issues.

**Comment by teevans** [comment]
@dwbrown2 - Threw some language in around that - Verrrrry open to feedback and criticism.

**Comment by dwbrown2** [comment]
Typo fix + minor suggestions! 

"We never want to miss our communicated release date, but sometimes it happens. We will only publish releases when we as a team feel like we're not delivering our best possible work product. Generally speaking, if we don't release on time, we have more work to complete before we feel like we're putting our best foot forward. Occasionally this happens, and when it does, we will communicate through our RC release notes what the new anticipated release date is. We will, at a minimum, have RC images available by the planned release date. We will also regularly cut RC images every few days until the anticipated launch date."

**Comment by teevans** [comment]
Changes made!

**Comment by dwbrown2** [comment]
Sorry, one mistaken on my part... "We will only _delay_ releases..."

**Review by dwbrown2 — APPROVED** [review]

**Pull request merged**
