### PR TITLE
add information on new oidc helm value

### PR DESCRIPTION
**Pull request by nickcurie**
## Related issue #

https://kubecost.atlassian.net/browse/SELFHOST-304

## Proposed Changes
Added information about a new OIDC helm value `skipOnlineTokenValidation`

### CODE REVIEW

**Comment by srpomeroy** [comment]
@nickcurie Will using this parameter also fix the Auth0 issues noted in the doc?

**Comment by nickcurie** [comment]
At a glance I would say yes, though I think @kaelanspatel might be better equipped to answer that question. Presumably if an auth0 user has the skipOnlineValidation enabled then we'd just verify the token locally so introspection is not required

**Review by srpomeroy — APPROVED** [review]
LGTM. Is this available in a current release or slated for 1.107?

**Comment by nickcurie** [comment]
This will be 1.107

**Review by bstuder99 — APPROVED** [review]

**Comment by nickcurie** [comment]
Oops sorry guys looks like this is meant to be in 1.106. I am cherry-picking the changes now

**Pull request merged**
