### PR TITLE
aws-cur-best-practice

### PR DESCRIPTION
**Pull request by jessegoodier**

### CODE REVIEW

**Review by mmurph3 — COMMENTED** [review]
@jessegoodier , Chris M. brought up a good point. Could we add more context here to make it more clear on what config files need to be downloaded and to whether it applies to account where kubecost primary lives or master payer? https://github.com/kubecost/docs/pull/651/commits/8e42f1d89b785d5fa84506608c3376836a34ad69#diff-fb0c175b18f0ce22792df1c597d32896179f566431ee6da902d1cb7b51401415R117

**Comment by jessegoodier** [comment]
Yes! I think that's the last step. will try to get this out soon. Feel free to co-author as well @mmurph3 and Chris M.

**Comment by jessegoodier** [comment]
@mmurph3 
added link to policy docs. I believe this is good to go.

**Comment by jessegoodier** [comment]
@bstuder99 this guide is meant to be our best practice for setting up the CUR with Kubecost. I think some links from https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations

and the navbar would be useful. Do you mind taking lead on that?

**Comment by bstuder99** [comment]
Little curious about the user journey involved in using this doc. This is still considered a complete AWS integration, just as part of a multi-cloud setup, correct? Is the idea that we should direct users here instead of our regular AWS integration guide as long as their environment meets the three stated conditions at the top of the article?

**Comment by jessegoodier** [comment]
> Little curious about the user journey involved in using this doc. This is still considered a complete AWS integration, just as part of a multi-cloud setup, correct? Is the idea that we should direct users here instead of our regular AWS integration guide as long as their environment meets the three stated conditions at the top of the article?

You got it Brett. See latest commit for potential wording.

**Comment by bstuder99** [comment]
Ok, I've gone through with a few edits. Everything looks good

**Review by bstuder99 — DISMISSED** [review]

**Comment by jessegoodier** [comment]
@bstuder99 had to merge in main conflicts

**Review by bstuder99 — APPROVED** [review]

**Review by chipzoller — COMMENTED** [review]
Based on the image refactoring proposed in #698, I would suggest a couple things:

1. Make image captions descriptive of the image itself because they also function as alt text.
2. Begin the path reference with a forward slash. I found that GitBook will not interpret this correctly if it is later indented in a structured block. Standardizing on leading forward slash is also fairly common for projects which use a root-level directory for images and assets.

**Comment by jessegoodier** [comment]
> Based on the image refactoring proposed in #698, I would suggest a couple things:
> 
> 1. Make image captions descriptive of the image itself because they also function as alt text.
> 2. Begin the path reference with a forward slash. I found that GitBook will not interpret this correctly if it is later indented in a structured block. Standardizing on leading forward slash is also fairly common for projects which use a root-level directory for images and assets.

100% feel free to start a new PR on this. @bstuder99, see above. also feel free to help out if you have time.

**Pull request merged**
