### PR TITLE
enterprise upgrade compatibility

### PR DESCRIPTION
**Pull request by jessegoodier**
1st pass at advice on agent > primary compatibility. 

Need some help @bstuder99 especially with formatting and nav bar changes.

### CODE REVIEW

**Comment by jessegoodier** [comment]
> Couple notes. Have already incorporated most of my feedback into docs edits:
> 
> * Are agent clusters and secondary clusters synonymous? Want to make sure the language we use is precise. yes, exactly.
> * This looks like a new doc? We need to still update summary.md. Would this belong in the Troubleshooting section, or Advanced Configuration? I'll leave nav to others. probably link from here though https://docs.kubecost.com/install-and-configure/install/multi-cluster
> * Is this doc going to have to be updated routinely over time as new Kubecost versions come out? ideally with the release
> * Can we link to release notes also? for sure

**Comment by bstuder99** [comment]
Ok, summary.md has been updated and the release notes link has been added. I personally don't like the idea of a living doc that needs monthly updates, I think it might be better to provide the oldest recommended agent version, some version ideally in the last few months which can be updated more casually.

**Comment by thomasvn** [comment]
@jessegoodier How is testing performed for the multi-cluster compatibility matrix? Is this currently done manually with differing primary & agent versions?

**Comment by jessegoodier** [comment]
To my knowledge, there hasn't been a breaking change between primary and secondary enterprise versions in years/ever.

IMO: It would come down to things that we are aware of like prom label (pod_name) or etl format changes that would impact single cluster upgrades anyway. 

Do you have other concerns?

One of the goal of this doc is to help customers understand the low risk of version upgrades and version drift.

**Comment by thomasvn** [comment]
I agree that version drift between primary and agent (secondary) is _generally_ low/medium risk. But I'm hesitant to be telling users that this is an officially supported state of running Kubecost.

Small changes to the Helm chart, the Prometheus subchart (e.g. metric collection & metric relabeling), or the backend's ETL pipeline (e.g. introduction of weekly ETLs) can have an impact on the user's deployment.

If we do plan to roll out this doc, I think we should clearly communicate that there is some risk in having version drift between primary and agent (secondary). The biggest risk being data integrity.

**Pull request closed without merging**
