### PR TITLE
Create kubecost-cloud-architecture.md

### PR DESCRIPTION
**Pull request by bstuder99**
Creation of the first of hopefully many Kubecost Cloud docs. For this doc, I think we should add an additional paragraph in the Architecture Overview section explaining what interactions are displayed in the graphic.

### CODE REVIEW

**Comment by srpomeroy** [comment]
@bstuder99 I pushed a commit for updating the nav.

**Comment by jessegoodier** [comment]
What do you think of these changes?
also, @srpomeroy 
image

**Comment by bstuder99** [comment]
Also wondering if we needed to actually label Prometheus? Will the logo be universally understood?

**Comment by jessegoodier** [comment]
> Also wondering if we needed to actually label Prometheus? Will the logo be universally understood?

Maybe make it much smaller? I good with or without it.

**Comment by bstuder99** [comment]
Ok, the chart has been replaced in kubecost/docs/images, so no changes on this doc have to be made. The link has already updated.

**Review by jessegoodier — APPROVED** [review]
can you add an s to kube-state-metrics? looks good.

**Pull request merged**
