### PR TITLE
Moves files into Using Kubecost folder

### PR DESCRIPTION
**Pull request by bstuder99**
## Proposed Changes

Continues moving files into their correct locations, mostly focuses on Using Kubecost docs. Also updates Local Disks and Cluster Roles docs to display correctly. Reorganizes Architecture folder docs order.

### CODE REVIEW

**Review by chipzoller — COMMENTED** [review]
Even though CI is passing, you're still verifying these links are good yourself via the GitBook preview site, right?

**Comment by bstuder99** [comment]
Yes.

**Comment by bstuder99** [comment]
I'm going through image links and verifying them still

**Comment by chipzoller** [comment]
When you're actively working on a PR and it's not done, either mark it as draft or wait until you feel it is complete before asking for review. This helps signal when you'd like to get eyes on it at your convenience.

**Comment by thomasvn** [comment]
@bstuder99 Thanks for moving "Kubecost Cluster Roles" to the Architecture section!

**Review by thomasvn — APPROVED** [review]

**Pull request merged**
