### PR TITLE
clarification on estimated savings calculations

### PR DESCRIPTION
**Pull request by mmurph3**

### CODE REVIEW

**Review by kwombach12 — CHANGES_REQUESTED** [review]
I'm not sure I love this phrasing. I would suggest instead "The total estimated monthly savings shown is 60% of the sum of all the savings 'cards'. In our experience, teams are not able to realize the total sum of all the savings cards due to overlapping savings (container & cluster sizing for example), application/workload constraints, or other organizational limitations.

**Comment by chipzoller** [comment]
Ping @mmurph3

**Comment by chipzoller** [comment]
@mmurph3, final bump.

**Review by mmurph3 — COMMENTED** [review]
lgtm

**Pull request closed without merging**
