### PR TITLE
Include Helm value in federated-etl.md

### PR DESCRIPTION
**Pull request by thomasvn**
Update federated-etl.md to include corresponding Helm value which must be set

### CODE REVIEW

**Comment by thomasvn** [comment]
Made the following finding with @keithhand @mmurph3. Adding for review.

**Review by srpomeroy — DISMISSED** [review]
LGTM

**Comment by thomasvn** [comment]
@jessegoodier Good catch! I agree that each federated cluster requires a unique `cluster_id`. I've pushed a new commit.

Requesting another review @srpomeroy !

**Review by kaelanspatel — APPROVED** [review]
lgtm fwiw

Very slight caveat (no changes needed) but only `cluster_id` is needed for federated to work.

**Pull request merged**
