### PR TITLE
Fix efficiency dashboard image alignment

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: chipzoller <chipzoller@gmail.com>

## Proposed Changes

Fixes image alignment (my mistake in review) on the Efficiency dashboard.

### CODE REVIEW

**Review by kwombach12 — APPROVED** [review]
LGTM

**Comment by lemontrees123** [comment]
The documentation mentions that GPU and storage metrics will be factored into efficiency calculations in future releases. When is it expected? Is there a specific time plan?

**Comment by thomasvn** [comment]
@lemontrees123 Some level of GPU Efficiency will be supported in an upcoming v2.4 release. @chipzoller any corrections or added detail?

**Comment by lemontrees123** [comment]
> @lemontrees123 Some level of GPU Efficiency will be supported in an upcoming v2.4 release. @chipzoller any corrections or added detail?

Can you tell me when version 0.24 will be released

**Comment by chipzoller** [comment]
Nothing we can share at this time.

**Pull request merged**
