### PR TITLE
Added clarity to Azure Cloud Integration

### PR DESCRIPTION
**Pull request by thomasvn**
## Overview

When setting up Azure cloud integration, users have run into issues using the `.Values.kubecostProductConfigs.azureStorageSecretName`, and we have now recommended users begin using the alternative option `.Values.kubecostProductConfigs.cloudIntegrationSecret` originally created for multi-cloud configuration.

Update docs to reflect the new recommended config. Eventually update default Helm values, Helm templates, and kubecost-cost-model as well.

## Related Issue

- https://github.com/kubecost/cost-analyzer-helm-chart/issues/1430

### CODE REVIEW

**Comment by bstuder99** [comment]
This looks good for the most part. Is there a reason we're scrapping most of the troubleshooting section?

**Comment by thomasvn** [comment]
Didn't scrap the troubleshoot section! I tried to convert its long-form paragraph style to quicker bullet points. Let me know if it's caused more confusion though, or if it's missing some key info!

**Comment by bstuder99** [comment]
I definitely don't mind brevity, but I think the density of info might make it harder to troubleshoot. Let me revisit this with proposed changes before approving/merging.

**Comment by thomasvn** [comment]
Agh! Sorry I used `git rebase` when I should've used `git merge`. These are the relevant commits to review:

* https://github.com/kubecost/docs/pull/461/commits/b89370d5c5c4c7ca97a6ce70e463320c0a34c2eb
* https://github.com/kubecost/docs/pull/461/commits/e755e8c7c6537ba043de2463c506851d2f382593
* https://github.com/kubecost/docs/pull/461/commits/ce68e467ba1c45975cd21075197b8188316fc54a
* https://github.com/kubecost/docs/pull/461/commits/8f878ae5f47f0f98e3e5404acbd2cbe116e7a3f4
* https://github.com/kubecost/docs/pull/461/commits/1849c3f202d459f7d556e8da7905a7e7e7d7d52c

Summary of revisions:
* More clarity & formatting changes to `azure-out-of-cluster.md` since in an effort to deprecate `.Values.kubecostProductConfigs.azureStorage*` in favor of `cloudIntegrationSecret`
* Update `multi-cloud.md` to also reflect these changes
* Condense troubleshooting section to bullet points instead of paragraphs
* Include comment on error message about `/var/azure-storage-config/azure-sroage-config.json` in troubleshooting and debugging section

**Review by bstuder99 — CHANGES_REQUESTED** [review]
Lot going on here, I added a couple notes about how Notes are formatted but aside from that, this looks good.

**Comment by thomasvn** [comment]
Made the change requested!

**Review by bstuder99 — APPROVED** [review]

**Pull request merged**
