### PR TITLE
Remove recording rules section

### PR DESCRIPTION
**Pull request by AjayTripathy**
We no longer need recording rules here.

### CODE REVIEW

**Comment by dwbrown2** [comment]
Are recording rules optional now or do they truly have no impact?

**Comment by AjayTripathy** [comment]
They should now have no impact.

**Review by ivankube — APPROVED** [review]
LGTM

**Comment by srpomeroy** [comment]
@AjayTripathy [Should we remove the recording rules from the helm chart?](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L524-L555)

**Comment by srpomeroy** [comment]
Merged updates separately.

**Pull request closed without merging**
