### PR TITLE
Update add-key.md

### PR DESCRIPTION
**Pull request by srpomeroy**

### CODE REVIEW

**Review by MikeFindsThings — APPROVED** [review]
Tested, LGTM.

**Comment by thomasvn** [comment]
@srpomeroy Thank you for this update! Validated it's in accordance with Helm chart

https://github.com/kubecost/cost-analyzer-helm-chart/blob/31ce9c2172849d4d042eecf7b7d920f6165d0864/cost-analyzer/values.yaml#L3395-L3399

**Comment by thomasvn** [comment]
@srpomeroy Looks like link checker is failing on the following. May need to add the link to `.lycheeignore` file?

```
* [429] [https://www.gnu.org/software/wget/](https://www.gnu.org/software/wget/) | Failed: Network error: Too Many Requests
```

**Comment by jessegoodier** [comment]
> @srpomeroy Looks like link checker is failing on the following. May need to add the link to `.lycheeignore` file?
> 
> ```
> * [429] [https://www.gnu.org/software/wget/](https://www.gnu.org/software/wget/) | Failed: Network error: Too Many Requests
> ```

just a rate limit? Merged.

**Pull request merged**
