### PR TITLE
Successful Enterprise Support Engagement

### PR DESCRIPTION
**Pull request by mmurph3**

### CODE REVIEW

**Comment by chipzoller** [comment]
It looks like there is some redundancy/conflict here with #1104. What's the plan?

**Comment by mmurph3** [comment]
@chipzoller - Want to add some docs to improve the support process and educate our users. Open to feedback.

**Comment by chipzoller** [comment]
Right, I understand that, but you have duplication between your two PRs.

**Review by thomasvn — APPROVED** [review]
Thanks @mmurph3 !

**Comment by thomasvn** [comment]
I think we should merge this into `main` first, then make sure to update #1104 with the new changes from `main` and also resolve any outstanding merge conflicts.

**Pull request merged**
