### PR TITLE
Update and rename community-getting-started.md to code-contribution.md

### PR DESCRIPTION
**Pull request by bstuder99**
Overhauled content to be more concise, style changes, corrected broken links and formatting, removed excessive social media links and filler phrases

### CODE REVIEW

**Comment by srpomeroy** [comment]
I vote we remove this doc. Its existence was intended to guide people when contributing to our original open-source cost-model repo. That has since been renamed OpenCost and moved to its own dedicated GH org with accompanying documentation.

Your thoughts @dwbrown2 & @mattray ?

**Comment by dwbrown2** [comment]
Think there's some good points in here... do we have all mentioned in OpenCost docs today? If so, I'm not opposed to removing. That said we do have other Kubecost OSS projects that others can contribute to.

**Comment by bstuder99** [comment]
So we have this doc that is linked to from the OpenCost docs: https://github.com/opencost/opencost/blob/develop/CONTRIBUTING.md

**Comment by bstuder99** [comment]
@dwbrown2 currently cleaning up PRs, can you elaborate on other Kubecost OSS projects besides OpenCost that this content could be relevant for? Want to finalize whether we remove this doc or not

**Comment by dwbrown2** [comment]
You can see our other OSS projects: https://github.com/kubecost/

I'm not sure what would be most relevant. Best to check with eng team.

**Comment by srpomeroy** [comment]
[List of Kubecost-owned OSS projects that this doc should reference for now.](https://kubecost.slack.com/archives/GNS5G863C/p1667488880023419)

[docs](https://github.com/kubecost/docs)
[events](https://github.com/kubecost/events)
[cost-analyzer-helm-chart](https://github.com/kubecost/cost-analyzer-helm-chart)
[kubecost-lens-extension](https://github.com/kubecost/kubecost-lens-extension)
[kubectl-cost](https://github.com/kubecost/kubectl-cost)
[cluster-turndown](https://github.com/kubecost/cluster-turndown)

**Comment by bstuder99** [comment]
So for now should we push the updates I've made as is? I can work on a second PR to reflect Stackwatch OSS projects with this feedback.

**Comment by srpomeroy** [comment]
I would not. It still references specifically how to build cost-model, which is now OpenCost.
Let me make some tweaks tomorrow.

**Comment by bstuder99** [comment]
Ok, let me do another passthrough today and fix it up.

**Comment by bstuder99** [comment]
I've added a section on OSS projects as detailed in the thread. If we want to delete this doc in its updated state or make additional changes, we should track it in a new PR.

**Pull request merged**
