### PR TITLE
Adds consistency to how we refer to Kubecost v2.0+

### PR DESCRIPTION
**Pull request by thomasvn**
## Related Issue

N/A

## Proposed Changes

No longer references v2.0, v2.x, or v2.x.x. I'm open to standardizing on something that isn't `v2.0+` as well.

### CODE REVIEW

**Review by srpomeroy — DISMISSED** [review]
This LGTM.

@chipzoller @kwombach12 @joe-terrible and input from you on how we should refer to versions?

**Comment by chipzoller** [comment]
It's more common to express this as simply "v2" when we mean major version 2 and all following minor versions.

**Comment by thomasvn** [comment]
@chipzoller I'm ok with standardizing on `v2` instead!

**Comment by chipzoller** [comment]
Definitely don't block on me here though.

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
