### PR TITLE
single line install

### PR DESCRIPTION
**Pull request by jessegoodier**
single line install
fix links
spelling

### CODE REVIEW

**Comment by bstuder99** [comment]
Looks good, but for installation edits, I just want @kwombach12 to look this over as well

**Comment by kwombach12** [comment]
LGTM!

**Review by bstuder99 — DISMISSED** [review]

**Comment by jessegoodier** [comment]
small improvement to the helm install command. please re-approve @bstuder99 
thanks!

**Review by kwombach12 — APPROVED** [review]
LGTM

**Review by bstuder99 — APPROVED** [review]

**Pull request merged**
