### PR TITLE
Adds network cost calculation methodology

### LINKED ISSUE #393: Document Network Cost Calclulation Methodology
1. With just the daemonset enabled
2. With the daemonset enabled + CUR enabled
3.  With just the CUR enabled.

### PR DESCRIPTION
**Pull request by srpomeroy**
Replaces #397 
Resolves #393

### CODE REVIEW

**Comment by srpomeroy** [comment]
@bstuder99 I merged the docs. Can I get a style review? Thanks!

**Comment by bstuder99** [comment]
Style is fine, but in regard to this section:
"These prices will be based on public API pricing, however, so the exact cost value you see might be incorrect." I was just talking with Thomas about the Network Costs page prices differing slightly from what is displayed on the Allocation/Overview pages, and I'm assuming this is the same issue? Is there a disclaimer we can add in here if customers want to know how to get exact prices, or if they want to compare for accuracy somewhere else?

**Review by bstuder99 — DISMISSED** [review]

**Comment by jessegoodier** [comment]
updated and reverted commit to wrong branch.

**Review by praveenkumar0566 — APPROVED** [review]

**Comment by jessegoodier** [comment]
Background: @praveenkumar0566 helped review- thanks!

@srpomeroy, if you are good with my changes, please feel free to merge.

There will likely be some fine tuning, but this is still better than what we have.

**Comment by thomasvn** [comment]
@srpomeroy , @jessegoodier , @praveenkumar0566 Nice update!! It will certainly help to address many of the questions users have been asking!

I noticed that you added a `network-costs-configuration.md` file but it's not referenced in `SUMMARY.md` so it's not viewable through the file tree. Is that by design? Should we add it in?

**Comment by jessegoodier** [comment]
> @srpomeroy , @jessegoodier , @praveenkumar0566 Nice update!! It will certainly help to address many of the questions users have been asking!
> 
> 
> 
> I noticed that you added a `network-costs-configuration.md` file but it's not referenced in `SUMMARY.md` so it's not viewable through the file tree. Is that by design? Should we add it in?

Thanks! 
Please add it. I just don't know what I'm doing 🤣

Also please correct anything if you find mistakes.

**Pull request merged**
