### PR TITLE
Update cost-allocation.md

### PR DESCRIPTION
**Pull request by bstuder99**
Making some large updates to the Cost Allocation page. Still a WIP, multiple changes have not been completed

### CODE REVIEW

**Comment by bstuder99** [comment]
Changes are complete including new screenshots, explanations of new UI features, and cleaning up of formatting.

**Review by srpomeroy — COMMENTED** [review]
This is great @bstuder99!

Two pieces of feedback.
1. "Aggregate filters" is mentioned a few times. I hesitate to call our aggregations filters because they are showing all resources of that aggregation.
2. We support a wild card `*` in the filter section within edit reports. e.g. `namespace=kube*` would return any namespace that begins with `kube`. We should document this.

**Comment by bstuder99** [comment]
1. So when I use the aggregate filter term, it's because that interactive element's text is "Aggregate By". I can reword it when I'm not referring to the UI specifically, is there a better term for this?
2. You're right, I forgot to add that in there. Let me go back and do that.

**Comment by srpomeroy** [comment]
"Aggregate filter" can work for now. I honestly can't think of a better term to use.

**Review by srpomeroy — APPROVED** [review]

**Pull request merged**
