### PR TITLE
Collections APIs

### PR DESCRIPTION
**Pull request by nikovacevic**
## Related Issue

Closes https://team.atlassian.com/project/KUBEC-89
Closes https://kubecost.atlassian.net/browse/ENG-2523

## Proposed Changes

Adds documentation for all current Collections APIs.

### CODE REVIEW

**Comment by nikovacevic** [comment]
@kwombach12 would appreciate your eyes here. I suggest starting with the [index page](https://github.com/kubecost/docs/blob/niko/collections-apis/apis/collections-apis/index.md), which has a table of contents.

I have a few questions:

Do we like the breadcrumbs at the top of each page?

Are the pages well organized, or do we want to split them out more, or even combine some? (E.g. we could combine the managing APIs into one page, but it would be a very long page, and probably difficult to navigate.)

Do we want an introduction in the index page? How in depth? E.g.
* What is a Collection?
  * What is a Category?
  * What is a Group?
  * What is a Selector?
  * What is a Domain?
* What is the total cost of a Collection?
* What is the time series cost of a Collection?
* What is the complement cost of a Collection?

**Comment by srpomeroy** [comment]
Reminder: Once a structure has been decided on, you can add it to [SUMMARY.md](https://github.com/kubecost/docs/blob/221f7eebfff5ef13fd28923f0b7cc4610424dcab/SUMMARY.md?plain=1#L125-L149), and then you can view the live preview under the checks.

**Comment by nikovacevic** [comment]
Helpful! Thanks @srpomeroy .

**Comment by kwombach12** [comment]
> Do we like the breadcrumbs at the top of each page?

I love the breadcrumbs. Really nice work. 
 
> Are the pages well organized, or do we want to split them out more, or even combine some? (E.g. we could combine the managing APIs into one page, but it would be a very long page, and probably difficult to navigate.)

Personally, I like the organization. I thought the querying collection + querying categories, could be combined but I'm fine to leave them separate.

> Do we want an introduction in the index page? How in depth? E.g.

100% yes, this is critical IMO. We can use this info for the Collections UI docs as well.

> * What is a Collection?
>   
>   * What is a Category?
>   * What is a Group?
>   * What is a Selector?
>   * What is a Domain?
> * What is the total cost of a Collection?
> * What is the time series cost of a Collection?
> * What is the complement cost of a Collection?

**Comment by nikovacevic** [comment]
Thanks @kwombach12 -- I will try to draft up some introductory docs today. And we can merge the category/collection docs in the Table of Contents, no problem.

**Comment by nikovacevic** [comment]
@kwombach12 this is ready for final review

**Review by kwombach12 — APPROVED** [review]
This looks awesome Niko! @srpomeroy or @chipzoller may be a good idea to get a quick glance from y'all to give a fresh user perspective

**Comment by nikovacevic** [comment]
Thanks @kwombach12 . Going to merge, but would welcome feedback from @srpomeroy and @chipzoller .

**Pull request merged**
