### PR TITLE
Delete storage.md as it's outdated and now implicitly required.

### PR DESCRIPTION
**Pull request by thomasvn**
## Related issue

N/A

### CODE REVIEW

**Comment by bstuder99** [comment]
Were you intending to delete storage.md itself or just this reference to it?

**Comment by thomasvn** [comment]
I was going to delete the file itself, is that ok? Or do you prefer I just remove all references to it.

**Comment by bstuder99** [comment]
I'm not against that, as I think we'll still preserve it in a 1.x branch, but it would still need to be delisted from summary.md. I'll make the edit.

**Comment by bstuder99** [comment]
Oh I see you already made the edit. Let me review the link checker before we merge

**Review by bstuder99 — APPROVED** [review]

**Pull request merged**
