### PR TITLE
prom-label-warning

### PR DESCRIPTION
**Pull request by kirbsauce**
In response to the ask for issue being publicly documented, as a start.  https://github.com/kubecost/cost-analyzer-helm-chart/issues/102

### CODE REVIEW

**Comment by dwbrown2** [comment]
Nice! Only feedback is that this makes it sound a bit more severe than it is... what about this "may" happen or something similar... I've still never seen this actually happen in the wild.

**Comment by kirbsauce** [comment]
Thanks for the feedback, @dwbrown2.  I was actually on the fence with the tone, so thanks for the nudge.  I'll ease up a little bit.

**Comment by kirbsauce** [comment]
@dwbrown2 , updates look good?

**Comment by dwbrown2** [comment]
LGTM

**Pull request merged**
