### PR TITLE
Shift docs between "Advanced Configuration" and "Installation" navigation

### PR DESCRIPTION
**Pull request by thomasvn**
Move "Cloud Billing Integrations" and "Multi-cluster / Thanos" sections out of Advanced Configuration and into Installation navigation

### CODE REVIEW

**Comment by thomasvn** [comment]
@dwbrown2 Correct! I believe I've adjusted all links/references. This can be verified by clinking on all the links in the rich diff [here](https://github.com/kubecost/docs/pull/483/files?short_path=4f74b24#diff-4f74b24c8cd7466c1c46dc972d8e284ed47091160afda95a432cc000f2eceb4a). Let me know if I missed anything though!

**Review by bstuder99 — APPROVED** [review]

**Comment by srpomeroy** [comment]
> Like it! Would we potentially need to handle redirect or broken links?

As long as the file names are not changing, GitBooks will automatically handle the redirects.

Additionally, you can view a live preview of the changes by expanding the checks and clicking details on the `GitBook - gitbook.kubecost.com — Content is live on GitBook` check.

image

**Comment by bstuder99** [comment]
@srpomeroy Good to know, so if we restructure our left nav, it won't break everything? This will be good to know if we opt for that mapping approach in the future.

**Comment by thomasvn** [comment]
@srpomeroy Thanks for clarifying, and sharing the screenshot! I misinterpreted the original question there.

**Pull request merged**
