### PR TITLE
Repair broken links and SSL

### PR DESCRIPTION
**Pull request by srpomeroy**
Fixes:

* Replace https://github.com/kubecost/docs/blob/main with the relative path
* Replace https://guide.zendesk.com with the relative path
* Replace https://docs.kubecost.com with the relative path
* Ensure https is used for links when available

### CODE REVIEW

**Comment by bstuder99** [comment]
So going forward, do we want to crosslink Kubecost articles using the original .md files?

**Review by bstuder99 — APPROVED** [review]

**Comment by bstuder99** [comment]
Curious when the preceding folder/container article needs to be referenced in the link

**Comment by srpomeroy** [comment]
> Curious when the preceding folder/container article needs to be referenced in the link

It technically shouldn't be needed. I am doing it when known to fix some "health checks" in ahrefs about redirects.
image


> So going forward, do we want to crosslink Kubecost articles using the original .md files?

Not sure I follow. Links can be to the slug (/install-and-configure/install) or the md (install.md) file

**Review by bstuder99 — DISMISSED** [review]

**Review by thomasvn — APPROVED** [review]
Looks good! As a future todo, we should set up an integration to lint the markdown file and also check the following rules for each PR:

- Replace https://github.com/kubecost/docs/blob/main with the relative path
- Replace https://guide.zendesk.com/ with the relative path
- Replace https://docs.kubecost.com/ with the relative path
- Ensure https is used for links when available

**Comment by srpomeroy** [comment]
> Looks good! As a future todo, we should set up an integration to lint check the markdown file and also check the following rules for each PR:
> 
> * Replace https://github.com/kubecost/docs/blob/main with the relative path
> * Replace https://guide.zendesk.com/ with the relative path
> * Replace https://docs.kubecost.com/ with the relative path
> * Ensure https is used for links when available

Yes! I was playing around with linting tools in a personal repo. Was planing on implementing next week. Do you have one you’ve used that you like? All the ones I’ve used previously are no longer maintained.

**Review by thomasvn — APPROVED** [review]

**Comment by thomasvn** [comment]
@srpomeroy I don't have any existing linting tool that I use or like, but I did have on my Todo to explore some! And also to dive into this repo's Github Actions.

**Comment by srpomeroy** [comment]
> @srpomeroy I don't have any existing linting tool that I use or like, but I did have on my Todo to explore some! And also to dive into this repo's Github Actions.

Yeah, same. We need a backlog and some coordination.

**Pull request merged**
