### PR TITLE
Update ingress-examples.md

### LINKED ISSUE #766: [Enhancement] Refine Ingress Warning
### Description

Strenghthen our ingress warning so its more clear to users that their endpoint is open to the world and that we recommend securing it.

### PR DESCRIPTION
**Pull request by kwombach12**
added more urgency to the ingress controls warning.

## Related issue #
Closes #766

### CODE REVIEW

**Review by chipzoller — COMMENTED** [review]
Creation of an Ingress resource doesn't necessarily involve literally exposing an application "to the world". Most Ingress host names are actually only internally-accessible hosts and not those publicly accessible. This could stand to be reworded to something like: "Please exercise caution when exposing Kubecost via an Ingress controller especially if there is no authentication in use."

**Comment by kwombach12** [comment]
@chipzoller ok cool thanks for sharing. I like your proposed updates

**Comment by chipzoller** [comment]
Ping @jessegoodier and @thomasvn for input especially re. the authentication comment.

**Review by jessegoodier — APPROVED** [review]
lgtm

**Comment by kwombach12** [comment]
@chipzoller @thomasvn Do we have sign-off from y'all to merge?

**Review by chipzoller — APPROVED** [review]
LGTM

**Pull request merged**
