### PR TITLE
Grafana Cloud Integration Documentation

### PR DESCRIPTION
**Pull request by elenalape**
This PR adds instructions on how to set up Kubecost to use Grafana Cloud's managed Prometheus as a data source.

### CODE REVIEW

**Comment by dwbrown2** [comment]
Do we currently have a target publish date in mind?

**Comment by AjayTripathy** [comment]
Will defer to Elena but I'm supportive of any date! This has been working for some time.

**Comment by elenalape** [comment]
Ajay is right, it has been working for some time! We can merge as soon as now, the launch blog post will follow.

**Comment by kbrwn** [comment]
LGTM!

**Review by kbrwn — APPROVED** [review]

**Comment by dwbrown2** [comment]
@kbrwn this was not ready to be merged. can we please revert.

**Pull request merged**
