### PR TITLE
Update network-allocation.md

### PR DESCRIPTION
**Pull request by kirbsauce**
minor typo

### CODE REVIEW

**Review by AjayTripathy — APPROVED** [review]

**Comment by dwbrown2** [comment]
Thanks for the fix! Feel free to merge when ready @kirbsauce :)

**Comment by kirbsauce** [comment]
@dwbrown2 , I think I need write access?

**Comment by AjayTripathy** [comment]
I think you probably want to be added to our company account, but I'll merge this now for you.

**Comment by kirbsauce** [comment]
thanks @AjayTripathy , i'll get added to the account to reduce the back-forth.

**Pull request merged**
