### PR TITLE
2/26 update to 'product-udpates'

### PR DESCRIPTION
**Pull request by kwombach12**

### CODE REVIEW

**Comment by bstuder99** [comment]
Hey, you're actually making this change in the docs repo in a delisted article. Can you port these changes over in our `docs-cloud` repo? With versioning, it will be the most up to date resource for cloud docs.

**Comment by kwombach12** [comment]
> Hey, you're actually making this change in the docs repo in a delisted article. Can you port these changes over in our `docs-cloud` repo? With versioning, it will be the most up to date resource for cloud docs.

Is this something you can help me with? I'm not sure how to do that.

**Comment by kwombach12** [comment]
@bstuder99 ok I think I moved it over to the right place - plz confirm

**Comment by biancaburtoiu** [comment]
New PR for reference: https://github.com/kubecost/docs-cloud/pull/4

**Pull request closed without merging**
