### PR TITLE
Remove legacy docs platform code

### PR DESCRIPTION
**Pull request by srpomeroy**
THese files are a holdover from the original GitHub Pages docs site. They should no longer be required.

### CODE REVIEW

**Comment by srpomeroy** [comment]
@dwbrown2 Any reason not to remove these items?

**Comment by dwbrown2** [comment]
@srpomeroy you guys have GA connected already yeah? If so, think you can get rid of the majority. 

I believe the `cname` file was a requirement of GH pages. Not 100% but that's the only one I'm not sure of.

**Comment by srpomeroy** [comment]
@dwbrown2 `CNAME` is definitely for GitHub Pages.
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain

**Comment by dwbrown2** [comment]
Thanks for confirming, think all are good to go then assuming GA is set.

**Pull request merged**
