### PR TITLE
Create configure-log-levels.md

### PR DESCRIPTION
**Pull request by bstuder99**
Doc creation for showing how to adjust log levels

Michael - feel free to remove the list of variables if we feel it's redundant or not necessary

### CODE REVIEW

**Review by michaelmdresser — APPROVED** [review]
Looks great!

**Comment by srpomeroy** [comment]
It's me playing devil's advocate again... As opposed to creating a net new doc, what do we think about slotting this into an existing doc? For example, https://github.com/kubecost/docs/blob/main/troubleshoot-install.md

**Comment by michaelmdresser** [comment]
That's a good doc for it! Log levels are mostly for troubleshooting, anyway!

**Comment by bstuder99** [comment]
Moved to https://github.com/kubecost/docs/pull/443

**Pull request closed without merging**
