### PR TITLE
New doc defining "Efficiency" and "Idle"

### PR DESCRIPTION
**Pull request by thomasvn**
Much of this information was pulled from getting-started.md and then placed into a new dedicated doc.

### CODE REVIEW

**Comment by thomasvn** [comment]
Requesting review from @kirbsauce since some of this content stems from his internal documentation.

**Comment by thomasvn** [comment]
@dwbrown2 according to git blame, you last wrote these [target values for idle](https://github.com/kubecost/docs/pull/502/files#diff-f007f6cb65740b71d33ebd4511fa8727d48a472d135ffd1bbef978237f9e6fa7L126-L128):

* CPU: 50%-65%
* Memory: 45%-60%
* Storage: 65%-80%

Do you think these target values are still roughly correct?

**Review by srpomeroy — COMMENTED** [review]
This is great @thomasvn. Technical content looks good.
@bstuder99 Can you give it a look over?

**Review by kirbsauce — DISMISSED** [review]
LGTM!

**Comment by AjayTripathy** [comment]
@dwbrown2 relevant to our discussion from this afternoon if you want to take a look!

**Review by srpomeroy — APPROVED** [review]

**Pull request merged**
