### PR TITLE
update arch diagrams and add cloud bill info

### PR DESCRIPTION
**Pull request by srpomeroy**
Images show broken when viewing doc due to the need to use full paths for ZenDesk docs.

### CODE REVIEW

**Review by jessegoodier — APPROVED** [review]
LGTM

**Comment by dwbrown2** [comment]
Thanks for these changes! @srpomeroy any reason to not keep network-costs marked as optional?

**Comment by srpomeroy** [comment]
@jessegoodier @mbolt35 and I had a conversation last week around the network-costs daemon set. Hoping to make it a default install in the future. Happy to revert and keep it marked as optional.

**Comment by dwbrown2** [comment]
Would be interested in feedback from others on making this default installed. Even if it's default on, though I still think it's ok to call this optional? 

IMO it would be great to have it bundled out of the box by default, but I worry that installing two separate daemonsets is a lot for most users. Not outright opposed, but I'd be more inclined to make it more discoverable within Kubecost UI first.

**Comment by srpomeroy** [comment]
Yep, that makes sense. I'll add optional to network costs. What is the second daemon set?

**Comment by dwbrown2** [comment]
node-exporter

**Comment by srpomeroy** [comment]
new PR to revert and add optional to other components.
https://github.com/kubecost/docs/pull/327

**Pull request merged**
