### PR TITLE
Creates Accessibility doc

### PR DESCRIPTION
**Pull request by bstuder99**
## Proposed Changes

Addresses' the thoguht behind Kubecost's UI palette to conform to accessibility standards. Can be updated over time as we make improvements to our typography as well.

### CODE REVIEW

**Comment by chipzoller** [comment]
Accessibility is not an aspect of an application's architecture. Suggest moving this to a different location.

**Review by kwombach12 — APPROVED** [review]
LGTM - @Annalillie do you mind taking a quick look here as well?

**Comment by Annalillie** [comment]
Looks good!!

**Comment by bstuder99** [comment]
Need a re-review on this to resolve some conflicts

**Review by kwombach12 — APPROVED** [review]
LGTM

**Pull request merged**
