### PR TITLE
Creates document on cost-analyzer ClusterRoles

### PR DESCRIPTION
**Pull request by bstuder99**

### CODE REVIEW

**Comment by bstuder99** [comment]
This is just the first pass on RBAC cluster roles, as our current documentation doesn't touch this topic too heavily. I'd like to expand this based on user requests over time or internally where we feel content is lacking. Our [SSO/SAML/RBAC doc](https://docs.kubecost.com/install-and-configure/advanced-configuration/user-management) mentions these three predefined RBAC roles: `admin`, `readonly`, and `editor`.

**Comment by bstuder99** [comment]
1. The idea was to be able to transcribe the content from the cluster-roles-template.yaml into a more readable, or at least condensed, format. Content may be subject to change like the rest of our documentation, as long as PRs affecting the original .yaml are noted during release, we should be able to make consistent updates to this doc.
2. Noted
3. Maybe you should open that issue with the specifics as to what is outdated/incorrect? Would like to know myself so I can update this doc.

**Comment by chipzoller** [comment]
> 1. The idea was to be able to transcribe the content from the cluster-roles-template.yaml into a more readable, or at least condensed, format. Content may be subject to change like the rest of our documentation, but as long as PRs affecting the original .yaml are noted during release, we should be able to make consistent updates to this doc.

I understand the idea but I think there's a more sustainable, less fragile way to do this which doesn't involve near-immediate obsolescence. For example:

"Kubecost requires `get`, `list`, and `watch` permissions over many common Kubernetes Pod and Pod controller resources such as Pods, Deployments, StatefulSets as well as other resources which factor into to cost analysis such as Namespaces, Nodes, Events, etc."

The "etc" part I'd list out all the specific resources. This provides the necessary information without showing the exact implementation details which are subject to change. End with providing a link to the actual ClusterRole(s) and state something generic like, "the current set of permissions can be found at the following location."

**Comment by chipzoller** [comment]
Created https://github.com/kubecost/cost-analyzer-helm-chart/issues/2658

**Review by jessegoodier — APPROVED** [review]
looks good to me.

**Pull request merged**
